export type Role = "Admin" | "Preparer" | "Reviewer";
export type Finding = { code: string; severity: "Error" | "Warning"; field: string; message: string };
export type UserSession = { id: string; email: string; roles: Role[] };
export type Dependent = {
  id?: string;
  firstName: string;
  lastName: string;
  ssn: string;
  relationship: string;
  qualifiesForChildTaxCredit: boolean;
  qualifiesForOtherDependentCredit: boolean;
};
export type FormData = {
  [key: string]: unknown;
  taxpayerFirstName: string;
  taxpayerLastName: string;
  taxpayerSsn: string;
  spouseFirstName: string;
  spouseLastName: string;
  spouseSsn: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  state: string;
  zipCode: string;
  foreignCountry: string;
  foreignProvince: string;
  foreignPostalCode: string;
  filingStatus: string;
  digitalAssetsQuestionYes: boolean;
  moreThanFourDependents: boolean;
  dependents: Dependent[];
  thirdPartyDesignee: boolean;
  designeeName: string;
  designeePhone: string;
  designeePin: string;
  routingNumber: string;
  bankAccountType: string;
  accountNumber: string;
  [key: `line${string}`]: unknown;
};
export type Submission = {
  id: string;
  status: string;
  createdAtUtc: string;
  updatedAtUtc: string;
  submittedAtUtc?: string | null;
  taxpayerName?: string;
  maskedSsn?: string;
};
export type FindingResponse = { isValid: boolean; findings: Finding[]; calculated?: Record<string, number> };
export type AdminUser = { id: string; email: string; roles: Role[]; lockoutEnd?: string | null };
export type StoredDocument = { id: string; createdAtUtc: string };