// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929125945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Api.Models.Form1040Data", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BankAccountType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesigneeName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesigneePhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DesigneePin")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DigitalAssetsQuestionYes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FilingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForeignCountry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignProvince")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line10")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line11a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line11b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line12")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line13a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line13b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line14")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line15")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line16")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line17")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line18")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line19")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1c")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1d")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1e")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1f")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1g")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1h")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line1i")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line1z")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line20")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line21")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line22")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line23")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line24")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line25a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line25b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line25c")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line25d")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line26")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line27")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line28")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line29")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line2a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line2b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line30")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line31")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line32")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line33")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line34")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line35a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line36")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line37")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line38")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line3a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line3b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line4a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line4b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line5a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line5b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line6a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line6b")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line7a")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Line8")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Line9")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MoreThanFourDependents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreparerFirmAddress")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparerFirmEin")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparerFirmName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparerName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparerPhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparerPtin")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreparerSelfEmployed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PreparerSignatureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutingNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseIdentityProtectionPin")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseLastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseOccupation")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SpouseSignatureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseSsn")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxpayerFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxpayerIdentityProtectionPin")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxpayerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxpayerOccupation")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TaxpayerSignatureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxpayerSsn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThirdPartyDesignee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("FormData");
                });

            modelBuilder.Entity("Api.Models.Form1040Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Form1040DataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("QualifiesForChildTaxCredit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QualifiesForOtherDependentCredit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Form1040DataId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("Api.Models.Form1040Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("Api.Models.GeneratedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("GeneratedDocuments");
                });

            modelBuilder.Entity("Api.Models.RevokedToken", b =>
                {
                    b.Property<string>("JwtId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("JwtId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("Api.Models.ValidationFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("ValidationFindings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Api.Models.Form1040Data", b =>
                {
                    b.HasOne("Api.Models.Form1040Submission", "Submission")
                        .WithOne("Form")
                        .HasForeignKey("Api.Models.Form1040Data", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Api.Models.Form1040Dependent", b =>
                {
                    b.HasOne("Api.Models.Form1040Data", null)
                        .WithMany("Dependents")
                        .HasForeignKey("Form1040DataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.Form1040Submission", b =>
                {
                    b.HasOne("Api.Models.ApplicationUser", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.GeneratedDocument", b =>
                {
                    b.HasOne("Api.Models.Form1040Submission", "Submission")
                        .WithMany("Documents")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Api.Models.ValidationFinding", b =>
                {
                    b.HasOne("Api.Models.Form1040Submission", "Submission")
                        .WithMany("Findings")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Models.ApplicationUser", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Api.Models.Form1040Data", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("Api.Models.Form1040Submission", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Findings");

                    b.Navigation("Form")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
