import type { Dependent, Finding, FormData } from "../../types";
import { filingStatuses, incomeLines, taxLines, paymentLines, computedLines, standardDeduction } from "./form1040";
import { ComputedLines, DateField, FieldErrors, MoneyField, TextField } from "../../components/FormFields";
import { money } from "../../utils/money";

type FormUpdate = (field: string, value: unknown) => void;
type FieldErrorsFor = (field: string) => Finding[];

export function FormEditor({ form, update, errorsFor }: { form: FormData; update: FormUpdate; errorsFor: FieldErrorsFor }) {
  return <form className="tax-form" onSubmit={(event) => event.preventDefault()}>
    <section className="form-section"><div className="form-section-title"><span className="step-number">01</span><div><h2>Taxpayer information</h2><p>Enter the identity and address information for this return.</p></div></div>
      <div className="form-grid three-col"><TextField label="First name" name="taxpayerFirstName" value={form.taxpayerFirstName} update={update} errors={errorsFor("taxpayer.name")} required /><TextField label="Last name" name="taxpayerLastName" value={form.taxpayerLastName} update={update} errors={errorsFor("taxpayer.name")} required /><TextField label="Social Security number" name="taxpayerSsn" value={form.taxpayerSsn} update={update} errors={errorsFor("taxpayer.ssn")} placeholder="###-##-####" inputMode="numeric" />
        <TextField label="Spouse first name" name="spouseFirstName" value={form.spouseFirstName} update={update} /><TextField label="Spouse last name" name="spouseLastName" value={form.spouseLastName} update={update} /><TextField label="Spouse SSN" name="spouseSsn" value={form.spouseSsn} update={update} errors={errorsFor("spouse.ssn")} placeholder="###-##-####" inputMode="numeric" />
        <TextField label="Street address" name="addressLine1" value={form.addressLine1} update={update} /><TextField label="Apartment or unit" name="addressLine2" value={form.addressLine2} update={update} /><TextField label="City" name="city" value={form.city} update={update} />
        <TextField label="State" name="state" value={form.state} update={update} /><TextField label="ZIP code" name="zipCode" value={form.zipCode} update={update} errors={errorsFor("taxpayer.zipCode")} placeholder="12345 or 12345-6789" /><TextField label="Foreign country (if applicable)" name="foreignCountry" value={form.foreignCountry} update={update} />
        <TextField label="Foreign province/state" name="foreignProvince" value={form.foreignProvince} update={update} /><TextField label="Foreign postal code" name="foreignPostalCode" value={form.foreignPostalCode} update={update} />
      </div>
      <label className="field-label">Filing status<select value={form.filingStatus} onChange={(event) => update("filingStatus", event.target.value)}><option value="">Choose filing status</option>{filingStatuses.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><FieldErrors errors={errorsFor("filingStatus")} /></label>
      <div className="standard-note">2025 standard deduction estimate for this status: <strong>{money(standardDeduction(form.filingStatus))}</strong>. The return calculation is recomputed by the server.</div>
      <fieldset className="choice-fieldset"><legend>At any time during 2025, did you receive, sell, exchange, or otherwise dispose of a digital asset?</legend><label className="radio-choice"><input type="radio" name="digitalAssetsQuestionYes" checked={!form.digitalAssetsQuestionYes} onChange={() => update("digitalAssetsQuestionYes", false)} /> No</label><label className="radio-choice"><input type="radio" name="digitalAssetsQuestionYes" checked={form.digitalAssetsQuestionYes} onChange={() => update("digitalAssetsQuestionYes", true)} /> Yes</label></fieldset>
    </section>

    <DependentsSection form={form} update={update} errorsFor={errorsFor} />
    <MoneySection title="Income" description="Enter applicable amounts from the source documents for each line." lines={incomeLines} form={form} update={update} computed={computedLines} />
    <MoneySection title="Adjustments, deductions, and tax" description="Enter the applicable amount for each numbered line. Calculated values are read-only." lines={taxLines} form={form} update={update} computed={computedLines} />
    <section className="form-section"><div className="form-section-title"><span className="step-number">05</span><div><h2>Payments, refund, and amount owed</h2><p>Enter applicable payment amounts and refund banking information.</p></div></div>
      <div className="money-grid">{paymentLines.map(line => <MoneyField key={line} line={line} value={form[`line${line}`]} update={update} errors={errorsFor(`line${line}`)} />)}</div>
      <ComputedLines lines={["25d", "33", "34", "37"]} form={form} />
      <div className="form-grid three-col banking-grid"><TextField label="Routing number" name="routingNumber" value={form.routingNumber} update={update} errors={errorsFor("routingNumber")} inputMode="numeric" /><TextField label="Account number" name="accountNumber" value={form.accountNumber} update={update} errors={errorsFor("accountNumber")} inputMode="numeric" /><label className="field-label">Account type<select value={form.bankAccountType} onChange={(event) => update("bankAccountType", event.target.value)}><option value="">Choose</option><option value="Checking">Checking</option><option value="Savings">Savings</option></select><FieldErrors errors={errorsFor("bankAccount")}/></label></div>
    </section>

    <section className="form-section"><div className="form-section-title"><span className="step-number">06</span><div><h2>Third-party designee and signatures</h2><p>Provide designee, taxpayer signature, and paid preparer details where applicable.</p></div></div>
      <label className="checkbox-row"><input type="checkbox" checked={form.thirdPartyDesignee} onChange={(event) => update("thirdPartyDesignee", event.target.checked)} /> Authorize a third-party designee</label>
      {form.thirdPartyDesignee && <div className="form-grid three-col"><TextField label="Designee name" name="designeeName" value={form.designeeName} update={update} /><TextField label="Designee phone" name="designeePhone" value={form.designeePhone} update={update} /><TextField label="Designee PIN" name="designeePin" value={form.designeePin} update={update} /></div>}
      <div className="form-grid three-col signature-grid"><TextField label="Taxpayer occupation" name="taxpayerOccupation" value={form.taxpayerOccupation} update={update} /><TextField label="Taxpayer identity protection PIN" name="taxpayerIdentityProtectionPin" value={form.taxpayerIdentityProtectionPin} update={update} /><DateField label="Taxpayer signature date" name="taxpayerSignatureDate" value={form.taxpayerSignatureDate} update={update} /><TextField label="Spouse occupation" name="spouseOccupation" value={form.spouseOccupation} update={update} /><TextField label="Spouse identity protection PIN" name="spouseIdentityProtectionPin" value={form.spouseIdentityProtectionPin} update={update} /><DateField label="Spouse signature date" name="spouseSignatureDate" value={form.spouseSignatureDate} update={update} /></div>
      <h3 className="subsection-heading">Paid preparer use</h3><div className="form-grid three-col"><TextField label="Preparer name" name="preparerName" value={form.preparerName} update={update} /><TextField label="Preparer phone" name="preparerPhone" value={form.preparerPhone} update={update} /><TextField label="Preparer PTIN" name="preparerPtin" value={form.preparerPtin} update={update} /><TextField label="Firm name" name="preparerFirmName" value={form.preparerFirmName} update={update} /><TextField label="Firm EIN" name="preparerFirmEin" value={form.preparerFirmEin} update={update} /><TextField label="Firm address" name="preparerFirmAddress" value={form.preparerFirmAddress} update={update} /><DateField label="Preparer signature date" name="preparerSignatureDate" value={form.preparerSignatureDate} update={update} /><label className="checkbox-row"><input type="checkbox" checked={Boolean(form.preparerSelfEmployed)} onChange={(event) => update("preparerSelfEmployed", event.target.checked)} /> Self-employed preparer</label></div>
    </section>
  </form>;
}

function DependentsSection({ form, update, errorsFor }: { form: FormData; update: FormUpdate; errorsFor: FieldErrorsFor }) {
  const dependents = form.dependents ?? [];
  function patch(index: number, changes: Partial<Dependent>) { update("dependents", dependents.map((dependent, itemIndex) => itemIndex === index ? { ...dependent, ...changes } : dependent)); }
  return <section className="form-section"><div className="form-section-title"><span className="step-number">02</span><div><h2>Dependents</h2><p>List up to four dependents. Additional dependents are indicated separately.</p></div></div>
    {dependents.map((dependent, index) => <fieldset className="dependent-card" key={dependent.id ?? index}><legend>Dependent {index + 1}</legend><div className="form-grid dependent-grid"><label className="field-label">First name<input value={dependent.firstName} onChange={(event) => patch(index, { firstName: event.target.value })} /></label><label className="field-label">Last name<input value={dependent.lastName} onChange={(event) => patch(index, { lastName: event.target.value })} /></label><label className="field-label">SSN<input value={dependent.ssn} placeholder="###-##-####" onChange={(event) => patch(index, { ssn: event.target.value })} /><FieldErrors errors={errorsFor(`dependents[${index}].ssn`)} /></label><label className="field-label">Relationship<input value={dependent.relationship} onChange={(event) => patch(index, { relationship: event.target.value })} /></label></div><div className="inline-checks"><label><input type="checkbox" checked={dependent.qualifiesForChildTaxCredit} onChange={(event) => patch(index, { qualifiesForChildTaxCredit: event.target.checked, qualifiesForOtherDependentCredit: false })} /> Child tax credit</label><label><input type="checkbox" checked={dependent.qualifiesForOtherDependentCredit} onChange={(event) => patch(index, { qualifiesForOtherDependentCredit: event.target.checked, qualifiesForChildTaxCredit: false })} /> Credit for other dependents</label><button className="remove-link" type="button" onClick={() => update("dependents", dependents.filter((_, itemIndex) => itemIndex !== index))}>Remove</button></div></fieldset>)}
    <div className="dependent-actions"><button className="secondary-button" type="button" disabled={dependents.length >= 4} onClick={() => update("dependents", [...dependents, { firstName: "", lastName: "", ssn: "", relationship: "", qualifiesForChildTaxCredit: false, qualifiesForOtherDependentCredit: false }])}>＋ Add dependent</button><label className="checkbox-row"><input type="checkbox" checked={Boolean(form.moreThanFourDependents)} onChange={(event) => update("moreThanFourDependents", event.target.checked)} /> More than four dependents</label></div>
    {errorsFor("dependents").map(finding => <p key={finding.code} className="field-error">{finding.message}</p>)}
  </section>;
}

function MoneySection({ title, description, lines, form, update, computed }: { title: string; description: string; lines: string[]; form: FormData; update: FormUpdate; computed: string[] }) {
  return <section className="form-section"><div className="form-section-title"><span className="step-number">{title === "Income" ? "03" : "04"}</span><div><h2>{title}</h2><p>{description}</p></div></div><div className="money-grid">{lines.map(line => <MoneyField key={line} line={line} value={form[`line${line}`]} update={update} />)}</div><ComputedLines lines={computed.filter(line => ["1z", "9", "11a", "14", "15", "24"].includes(line))} form={form} /></section>;
}

export function ReadOnlyForm({ form }: { form: FormData }) {
  const keyLines = ["1z", "9", "11a", "15", "24", "33", "34", "37"];
  return <section className="form-section read-only-card"><span className="eyebrow">RETURN INFORMATION</span><h2>{form.taxpayerFirstName} {form.taxpayerLastName}</h2><div className="read-only-grid"><div><span>Taxpayer SSN</span><strong>{form.taxpayerSsn}</strong></div><div><span>Filing status</span><strong>{filingStatuses.find(([value]) => value === form.filingStatus)?.[1] ?? "Not selected"}</strong></div><div><span>Digital assets</span><strong>{form.digitalAssetsQuestionYes ? "Yes" : "No"}</strong></div>{keyLines.map(line => <div key={line}><span>Line {line}</span><strong>{money(Number(form[`line${line}`] ?? 0))}</strong></div>)}</div><h3>Validation history</h3><p>Use “Validate submission” to review server-side findings. SSNs are masked for reviewer access.</p></section>;
}